ipni/index-provider

- command/daemon.go
- command/flags.go
- command/fsutil.go
- config/config.go
- config/identity.go
- config/init.go
- core/engine/engine.go
- internal/version/version.go
- internal/version/version_test.go
- main.go
Reformat the entire repo using `gofumpt -l -w` for consistency going forward.
Refactor small utility functions for better readability.
Update docs and leave TODOs where needed.
> Reformat code using `gofumpt`

- command/daemon.go
- command/flags.go
- command/init.go
- core/engine/engine_test.go
- internal/suppliers/callback.go
- internal/suppliers/callback_test.go
- internal/suppliers/car_supplier.go
Instantiate a CAR supplier that uses the same underlying datastore as
the engine, convert it to `CidCallback` and register it. Define a new
flag for daemon that allows configuration of CAR read option on how to
treat zero-length blocks.
Adjust the prefix of datastore entries produced by CAR supplier to avoid
clash since datastore is shared with engine and the supplier.
Add utility to convert a streaming CID supplier to the non-streaming
`CidCallback`. Note, we want to retain the streaming abilities
implemented already for future use, e.g. chunking of CID list etc.
Write tests that assert draining a streaming CID iterator is correct.
Unexport flags until they need to be exported and remove placeholders.
> Register CAR supplier in daemon engine

- core/engine/engine.go
- core/engine/engine_test.go
- core/engine/linksystem.go
- core/interface.go
- internal/suppliers/callback.go
- server/libp2p/protocol_test.go
This PR:
- Adds a `lookupKey` to identify the list of CIDs being advertised.
- Handles the relationship between `lookupKey` and list of CIDs, and generates the link for the list of CIDs structure so it can be ingested by indexers.
> Add lookupKey. Key-Cid mapping

- server/http/importcar_handler.go
- server/http/importcar_handler_test.go
- server/http/models.go
- server/http/server.go
Implement handler for POST requests to `admin/import/car` endpoint to
request import of a CAR file from a given path with optional key and
metadata.
> Implement admin server handler for importing CAR files

- command/daemon.go
- command/flags.go
- command/import.go
- command/net.go
- main.go
- server/http/importcar_handler_test.go
- server/http/server.go
Implement `import car` command that takes a path and optional lookup
key and metadata, then connects to the admin HTTP API to import it.
> Implement `import car` CLI command

- command/import.go
- command/net.go
- server/http/connect_handler.go
- server/http/error.go
- server/http/importcar_handler.go
- server/http/io.go
- server/http/models.go
- server/http/server.go
Define a dedicated error response type and assert that endpoints only
accept JSON as input.
Introduce empty response for Connect for consistency of JSON response.
Add utilities to marshal and unmarshal request/responses.
> Improve error handing in admin server

- Dockerfile
Add a dockerfile that builds the reference provider with a conditional
initialiazation build argument that is enabled by default. Note, the
docker image built as a result is meant for testing purposes only, since
once initialized it will contain a generated private key that is unsafe
to use in production.
> Containerize the provider by defining a `Dockerfile`

- core/engine/engine.go
- core/engine/engine_test.go
- core/engine/linksystem.go
- internal/utils/utils.go
- server/provider/libp2p/protocol_test.go
This PR:
- Removes the cast of `LookupKey` as CID by default.
- Forces users to register a proper callback in the engine to translate from `LookupKey` to list of CIDs.
_(@masih you were right. After tinkering a bit with the use of a default callback, it made the code really dirty and it wasn't actually  doing any good to users, as they had to still worry about storing the list of CIDs in the right format in the blockstore. Going with your approach, where the engine fails if no callback has been registered. Let me know what you think)_
> Engine fails if no callback has been registered

- core/engine/engine.go
- core/engine/linksystem.go
- server/provider/libp2p/handler.go
This PR adds `Error` and some `Debug` logs to the core engine.
> Add logs to core engine

- engine/engine.go
- engine/engine_test.go
- engine/linksystem.go
- interface.go
- internal/suppliers/car_supplier.go
- internal/utils/utils.go
- mock/interface.go
- server/admin/http/importcar_handler.go
- server/admin/http/models.go
Remove the `LookupKey` type in favour of `[]byte` that represents
"Context ID", an ID used already bo go-indexer-core to aggregate
metadata. For provider's purposes this results in 1:1 functionaly with
`LookupKey`, since a "Context ID" will always return the same list of
multihashes.
> Replace `LookupKey` concept with `ContextID`

- go.mod
- go.sum
This brings the provider in sync with the same commit of go-legs that the indexer is now using.
> Update to latest go-legs

- engine/engine.go
- engine/engine_test.go
- engine/linksystem.go
- errors.go
- interface.go
Export an explicit error type to signal that a `contextID` is never seen
before if given to `NotifyRemove`.
While at it, move the known error type for no registered callback out of
engine and onto `provider` package.
Update docs and add tests.
> Export explicit error types for unknwon `contextID`

- go.mod
- metadata/metadata.go
- metadata/metadata_test.go
Implement #52 
Define:
- Protocol Multicodec for using data transfer
- DataTransferMetadata
- Filecoin specific data
- Encoding and decoding rules (basically, use CBOR)
- Functions to encode/decode
Re: where to put this - perhaps it shouldn't be in this repo, but also, why not leave it here till we figure out a better place
Protocol decisions:
1. I feel pretty strongly the actual "protocol" is data transfer. Data Transfer should support multiple transport protocols and multiple exchange formats. The important thing this tells you is you are going to transfer this with the Data Transfer Protocol, regardless of the underlying transport. This doesn't mean there isn't a future raw "Graphsync" protocol -- IPFS might offer this at some point. Bitswap might too. But they are still distinct.
2. …
> Define Filecoin Metadata types

- go.mod
- go.sum
- metadata/metadata.go
- metadata/metadata_test.go
Uses @mvdan 's PR to go-ipld-prime so we can use a native cid.Cid with bind node, allowing our FilecoinV1Metadata to use a cid.Cid directly rather than a datamodel.Link
> Use native cid.Cid format in FilecoinV1Metadata struct

- Makefile
- cmd/provider/daemon.go
- config/config.go
- config/datastore.go
- config/ingest.go
- config/init.go
- e2e_retrieve_test.go
- engine/dscache.go
- engine/dscache_test.go
- engine/engine.go
- engine/engine_test.go
- engine/linksystem.go
- go.mod
- go.sum
- internal/cardatatransfer/cardatatransfer_test.go
- server/provider/libp2p/protocol_test.go
This PR uses a datastore-backed LRU cache.  Cache keys (link CIDs) are stored in memory, and the values (multihash chunks) are stored in a persistent datastore.  As new links/chunks are added to the cache, older items are removed when the cache is at capacity.  If a single linked list is more than the cache's current capacity, the cache is resized to hold the entire linked list. 
- Cache size is configurable
- Cache automatically expands to hold largest complete linked list
- Cache persisted across restarts
Fixes #37
Fixes #61
> Link cache is now datastore-backed LRU cache 

- config/adminserver.go
- config/types.go
- server/admin/http/server.go
Provide config type that encodes durations as golang duration strings instead of nanosecond value.  This makes the config file easier to read and use.
> Represent durations in config as golang duration strings, e.g. "30s"

- e2e_retrieve_test.go
- engine/engine.go
- engine/linksystem.go
- errors.go
- interface.go
- internal/suppliers/car_supplier.go
- server/admin/http/importcar_handler.go
- server/admin/http/importcar_handler_test.go
When the same content is put into the provider, reuse the existing set of entries instead of regenerating them.  If the contextID and metadata are also identical, then do not generate a new advertisement.
This PR includes an end-to-end test that:
- Tests that reimporting the same car file, with the same contextID and metadata, does not generate new advertisement
- Tests that reimporting the same car file, with the same contextID and different metadata, generates new advertisement that uses the same chain of entries as the first car advertisement.
Fixes #75
> Do not create new advertisement for same content

- server/admin/http/io.go
- server/admin/http/models.go
- server/admin/http/removecar_handler.go
- server/admin/http/removecar_handler_test.go
- server/admin/http/server.go
Implement a HTTP edpoint exposed on admin server that accepts context ID
associated to a CAR that is already imported and advertises its removal.
Note the endpoint does not implement removal by path alone. This is
because the CAR supplier only accepts put with explicit context ID. If
context ID can be generated as the hash of path, then that functionality
seem to be better housed on the admin CLI side or re-introduced in CAR
supplier itself then added to the admin server.
At the engine level, making the end to end functionality work depends
on:
- https://github.com/filecoin-project/storetheindex/pull/104
This commit focuses on the admin server interface only.
Fixes #77
> Implement admin server endpoint to remove CARs

- LICENSE.md
- README.md
Update README with a general overview of what the repo provides, along
with pointers to the CLI tooling and defaults.
Add lincese consistent with storetheindex and go-indexer-core.
See: [README rendered](https://github.com/filecoin-project/indexer-reference-provider/blob/2b4d27dbb9e34c5ee9b2ab70e5ef72ca06c40d40/README.md).
Fixes #84
> Update README and add LICENSE

- cmd/provider/flags.go
- cmd/provider/import.go
- cmd/provider/provider.go
- cmd/provider/remove.go
- cmd/provider/testdata/script/remove-car.txt
Implement a CLI command that advertises removal of a list of multihashes
previously advertised via importing a CAR file. The command accepts
either the key or the path by which the CAR was imported in order to
identify which CAR file to remove. For the command to work the CAR file
must have previously been advertised.
Note that an optional CAR path flag is added in this commit, since the
existing flag object is mandatory and used in `import car` sub-command.
Relates to:
- https://github.com/filecoin-project/indexer-reference-provider/pull/83
Fixes #78
> Implement `remove car` CLI command

- internal/cardatatransfer/cardatatransfer.go
- metadata/metadata.go
- metadata/metadata_test.go
Rename the `IsFree` field in `FileCoinV1Data` retrieval metadata to
`VerifiedDeal` so that it is consistent with the terminology used in
FileCoin `DealProposal`.
Note that the rename drops `Is` prefix to be consistent with the naming
of `FastRetrieval` field in metadata.
See:
- https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/market/deal.go
> Rename `IsFree` metadata field to `VerifiedDeal`

- .gitignore
- Dockerfile
- Makefile
- README.md
- config/config.go
This makes the binary executable and default repo directory names match the project name, making them more easily identified.
Import path names will be changed in a separate PR.
> Rename executable binary and default repo

- Makefile
This is necessary to build using `make` now that `cmd` is a separate module.
> Fix Makefile bin target to use correct modfile

- go.mod
- go.sum
Downgrade following dependencies to reduce churn on lotus side:
- github.com/libp2p/go-libp2p-quic-transport to `v0.11.2`
- github.com/ipfs/go-bitswap to `v0.3.4`
Use `replace` directive in `cmd/go.mod` so that the latest changes from
root module are pulled.
Relates to:
- https://github.com/filecoin-project/lotus/pull/7622
> Downgrade dependencies to reduce churn in lotus integration

- config/config.go
- config/config_test.go
This is useful when specifying a path for the datastore that is outside of the config root.
> Recognize absolute paths in config file

- cmd/provider/daemon.go
- engine/dscache.go
The index provider engine as well as its internal components, like
`dsCache` take an existing datastore instance and reuse it internally.
`dsChace` implements the `datastore.Datastore` interface by wapping the
existing instance. Since the instance is instantiated externally, it
should not be closed off by the provider `Engine` nor `dsChache`.
Instead, delegate the management of the datastore lifecycle to where it
is instantiated, i.e. the `daemon` command.
> Do not close the wrapped datastore used for caching

- cmd/provider/find.go
- cmd/provider/import.go
When importing a car file, the context ID was being computed incorrectly and was including the entire car file path in the context ID.  This PR fixes this so that only the sha256 hash is used to create the context ID.
For a demonstration of the wrong vs. correct calculation, see https://go.dev/play/p/cak7EJH1Y_y 
Find command also has clearer output.
> ContextID should be only sha256 hash

- cmd/go.sum
- go.mod
- go.sum
Upgrade to the latest go-legs which uses the same version of
go-libp2p-pubsub as the sofia miner
> Upgrade to latest go-legs

- config/adminserver.go
- config/bootstrap.go
- config/config.go
- config/datastore.go
- config/identity.go
- config/ingest.go
- config/init.go
- config/providerserver.go
- engine/engine.go
Add `New*` constructor for each of the sub config types with default
values.
Fixed #108
> Refactor config for easier instantiation with default values

- cmd/provider/find.go
- cmd/provider/import.go
- cmd/provider/remove.go
- engine/engine.go
- server/admin/http/removecar_handler.go
- server/admin/http/removecar_handler_test.go
Advertisements require valid metadata, even though metadata is not used for index removal.  This change creates a removal advertisement with valid, but empty, metadata.
Additional changes:
- Fix bad contextID creation in remove command
- Improve output of find, import, and remove commands
- Improve log messages: readable contextID, structured logging
Fixes issue #121
> Generate valid removal advertisements

- engine/linksystem.go
Set this flag when we resize. Otherwise we won't shrink the cache later.
> Set resized flag in generateChunks

- config/httppublisher.go
- config/httpserver.go
- config/ingest.go
- e2e_retrieve_test.go
- engine/engine.go
go-legs supports syncing over http. But the index provider hasn't been hooked up to start the http server.
This PR adds a config and logic to enable the http index provider via go-legs. It also includes a test in `e2e_retrieve_test.go` that syncs over http.
> Support http publisher

- Makefile
- cmd/go.mod
- cmd/go.sum
- cmd/provider/daemon.go
- engine/engine.go
- engine/engine_test.go
- go.mod
- go.sum
- interface.go
Republishes the latest advertisement on startup for the following reasons:
- Set the publisher's latest head CID
- Send last advertisement that may have been missed by new indexers that joined network during downtime
- Send last ads that was not published because of some reason that required provider restart
This change also stops the engine from logging the same errors that are also returned.  Errors should either be returned or logged, not both.
Fixes #145
> Republish latest advertisement on startup

- cmd/go.mod
- cmd/provider/get.go
- cmd/provider/internal/client.go
- cmd/provider/internal/client_store.go
- cmd/provider/internal/entries_iter.go
- cmd/provider/provider.go
- cmd/provider/verify_ingest.go
Implement a CLI command that gets the content of an advertisement from
a provider endpoint either via HTTP or over graphsync depending on the
given endpoint with option to print the entire list of multihashes.
> Implement command to list provider advertisement

- cmd/provider/doc.go
- cmd/provider/internal/entries_iter.go
- cmd/provider/list.go
- cmd/provider/verify_ingest.go
Add `provider verify-ingest` option to get the advertisement by directly
connecting to a provider's grphsync endpoint and fetching either the
latest advertisement entries or entries belonging to a specific
advertisement CID.
> Add CLI command to verify ingestion by getting ad directly from provider

- cmd/provider/internal/client_store.go
In my last PR I didn't add the side-effect import which is needed to register these codecs.
> Register codecs for provider cli

- cmd/provider/flags.go
- cmd/provider/internal/client.go
- cmd/provider/internal/entries_iter.go
- cmd/provider/list.go
- cmd/provider/verify_ingest.go
Add option to `verify-ingest` to walk the chain of advertisement from
either a given CID or head up to a configured limit, and for each
encountered advertisement verify ingest.
Add the ability to limit entries chain sync when it is too long along
with output to tell the CLI user of their existence.
> Implement recursive ingest verification by walking the chain

- cmd/provider/list.go
- cmd/provider/verify_ingest.go
- config/ingest.go
`storetheindex` topic is updated to include network name. Make it
consistent here.
> Update the default topic name to be consistent with storetheindex

- .github/workflows/goreleaser-check.yml
- .github/workflows/releaser-bin.yml
- .gitignore
- .goreleaser.yaml
Use goreleaser to build and attach binaries for multiple platform to a
published release.
Add CI job to check goreleaser config for validity on change.
> Automatically Build and attach binaries to published releases

- engine/engine_test.go
- server/admin/http/importcar_handler_test.go
- server/admin/http/removecar_handler_test.go
- testutil/testutil.go
The `testutil` functions that use RNG, were creating a new instance of it
seeded with current unix time. This causes two main issues: 1)
randomness in tests is not deterministic, which makes reproducing
intermittent test failures difficult. 2) the implementation of current
system nano time is platform-specific and when tests are run
concurrently this can cause issues with duplicate generated values
across gorutines that expect unique values for testing purposes.
Fix this by requiring RNG in `testutil` and instantiate one explicitly
with a fixed seed in each test.
> Fix RNG used by `testutil` to avoid intermittent test failures

- cmd/go.mod
- cmd/go.sum
- engine/engine.go
- engine/option.go
- go.mod
- go.sum
- version.json
If the datatransfer publisher is configured with a miner ID, then that is included with pubsub messages.  It is used to allow lotus chain-nodes to authenticate the message for relay.
> Add option to configure miner ID for datatransfer publisher

- cmd/provider/internal/client.go
- cmd/provider/internal/client_store.go
- cmd/provider/internal/entries_iter.go
- cmd/provider/internal/options.go
- cmd/provider/list.go
- cmd/provider/verify_ingest.go
When encountering `NoEntries` CID, do not attempt to traverse it in
`provider` CLI.
Do not traverse entries of a removal advertisement even if a CID is
present. Instead, print useufl messages to signal such cases.
Improve output for human readability.
Fixes #179
> Handle `NoEntries` cid gracefully and improve cli output

- engine/engine.go
- engine/linksystem.go
- engine/linksystem_test.go
Given that the indexer protocol is now changed to only support
"remove all" advertisements, adjust code comments to remove suggestions
that explicit removal of multihashes is supported.
Do not attempt to resolve entries link that points to `schema.NoEntries`
special CID.
Add tests that assert both add and remove advertisements are
resolvable. But when content is removed, entry chunk corresponding to
earlier add advertisement for that content is no longer found.
Relates to: https://github.com/filecoin-project/storetheindex/pull/225
Fixes #174
> Do not resolve `schema.NoEntries` CID

- cmd/go.mod
- cmd/go.sum
- e2e_retrieve_test.go
- go.mod
- go.sum
- version.json
Upgrade dependency to `storetheindex` and `go-legs`.
Bump version in preparation for release.
> Upgrade indexing dependencies and bump version

- cmd/provider/internal/client.go
- cmd/provider/internal/client_store.go
- cmd/provider/internal/entries_iter.go
- cmd/provider/list.go
...In list.
I was testing this on an http endpoint and it was failing. I simplified the two flows into a single flow using the legs subscriber abstraction.
I also fixed a bug that prevented entries from showing in the list command.
> Use legs subscriber to abstract out the dtsync vs httpsync

- cmd/go.mod
- cmd/go.sum
- cmd/provider/internal/ad_stats.go
- cmd/provider/internal/client.go
- cmd/provider/internal/client_store.go
- cmd/provider/internal/ingest_verifier.go
- cmd/provider/internal/options.go
- cmd/provider/list.go
- cmd/provider/printer.go
- cmd/provider/verify_ingest.go
Add functionality to print statistics about the walked advertisement
chain, such as: total removal and non-removal ads, unique context ID
count, distribution of multihashes and chunks over advertisements, etc.
Add logic to retry syncing of ad and its entries, resuming from the last
successfully synced node in DAG.
Restructure verification logic to make command main package less
cluttered.
> Print ad chain stats and retry when syncing ads

- cmd/go.mod
- cmd/go.sum
- engine/engine_api_test.go
- engine/engine_test.go
- engine/linksystem_test.go
- engine/slicemhiter_test.go
- go.mod
- go.sum
- mock/interface.go
Re-implement the engine tests that assert advertisement publish with
data transfer publisher works correctly with expected extra gossip data
Add various tests that assert returned error types.
Re-generate mock files.
Upgrade to the latest go-legs
Remove the old tests that poked inside the engine, and move all engine
tests to a separate `_test` package.
> Re-implement engine tests and re-enable all tests

- README.md
- cardatatransfer/doc.go
- cmd/provider/daemon.go
- engine/engine.go
- engine/engine_test.go
- engine/example_test.go
- engine/linksystem.go
- engine/linksystem_test.go
- errors.go
- interface.go
- mock/interface.go
- server/admin/http/importcar_handler_test.go
- server/admin/http/removecar_handler_test.go
- supplier/car_supplier.go
- supplier/car_supplier_test.go
- supplier/doc.go
Use a more specific term to descibe the hook used by the index provider
engine to list multihashes associated to a context ID:
`MultihashLister`, and update docs as needed.
> Rename `Callback` to a more specific name: `MultihashLister`

- metadata/graphsync_filecoinv1.go
- metadata/graphsync_filecoinv1.ipldsch
Add a dedicated IPLD schema type for GraphSyncFilecoinV1 metadata
protocol to replace the schema created using IPLD `Accumulate`.
Fixes: #82
> Replace IPLD accumulate with IPLD schema file

- cardatatransfer/cardatatransfer_test.go
- engine/chunker/cached_chunker_test.go
- engine/engine_test.go
- engine/linksystem_test.go
- go.mod
- metadata/graphsync_filecoinv1_test.go
- metadata/metadata_test.go
- server/admin/http/importcar_handler_test.go
- server/admin/http/removecar_handler_test.go
- testutil/testutil.go
Remove duplicate logic for random CID generation, which also results in
removing dependency to `go-ipfs-blocksutil` and more reproducible tests.
> Remove dependency to `go-ipfs-blocksutil` used only for testing

- cmd/provider/announce.go
- cmd/provider/flags.go
- cmd/provider/provider.go
- engine/engine.go
- server/admin/http/announce_handler.go
- server/admin/http/server.go
The `announce` command publishes an announce for the latest advertisement.  This is useful to get indexers to sync without having to publish a new advertisement.
Additional change: On daemon startup, initialize the daemon with the latest ad CID but do not publish it.  Publishing the ad CID is not useful since the daemon will not yet have bootstrapped to any peers.  Having the `announce` command is a better as it allows optional publishing once the daemon is ready.
> New announce command to announce latest advertisement

- version.json
Bump version in preparation for release
> Bump version to `0.6.0`

- engine/engine.go
- version.json
Fix error encoding in logs and bump version for release
> Fix encoding of error in logs when instantiating publisher

- version.json
Bump version to 0.7.0 in prep for release. Rationale for larger bump:
- go mod version upgrade.
> Bump version to `0.7.0` in preparation for release

- .gitignore
- Makefile
- The build system may not have bash shell installed, so do not use bash-specific shell flags.  Instead only assume standard bourne shell capabilities.
- Do not do `git fetch --tags` since it is usually not necessary and requires github access or explicitly setting `TAG`.
- Fix .gitignore to correctly ignore provider executable.
Fixes #223
> Do not assume build system has bash shell

- version.json
Bump version to release fixes in caching mechanism mainly. Note the
version is changed from `0.7.0` to `0.8.0` since the changes being
tagged also include removal of the `cmd` submodule.
> Bump version to `0.8.0` in preparation for release

- engine/chunker/cached_chunker.go
- engine/chunker/cached_chunker_test.go
- engine/engine.go
The existing behaviour will restore the cache regardless of whether the
purge-cache flag is set or not. The rationale for this behaviour was
that the Clear logic needed to know what caches to delete in the
first place.
This rationale no longer stands because of the changes to recovery from
corrupt cache introduced in earlier PRs. The Clear logic would delete
all entries in the datastore regardless to make sure that the datastore
size does not leak as a result of orphan cache entries for example.
The changes here, therefore, won't bother restoring the cache if it is
to be cleared.
Relates to:
- https://github.com/filecoin-project/index-provider/issues/237
> Do not bother restoring cache when purge cache is set

- engine/chunker/benchmark_test.go
- engine/chunker/cached_chunker.go
- engine/chunker/cached_chunker_api_test.go
- engine/chunker/cached_chunker_test.go
- testutil/testutil.go
The chunk cache only stored the root of a chunked entry chain. The cache
restore logic then traversed the DAG to resolve all child links. In a
case where the cache is large and the DAG is big it could be slow to
traverse the dag and resolve all the child links.
Instead of resolving them dynamically, store the child links with the
root link so that restoring the hash is fast and won't require
traversing the DAG. The trade-off however is slightly larger storage
consumption, where for each entry chain DAG a mapping of root link to
list of all links in the DAG is stored in the datastore.
Fixes: https://github.com/filecoin-project/index-provider/issues/237
> Cache links of a root entry instead of resolving them on the fly

- cmd/provider/announce.go
- cmd/provider/flags.go
- cmd/provider/provider.go
- engine/engine.go
- engine/host_to_maddr.go
- engine/host_to_maddr_test.go
- server/admin/http/announce_handler.go
- server/admin/http/io.go
- server/admin/http/models.go
- server/admin/http/server.go
The `announce-http` command manually announces the latest advertisement CID to a specific indexer over HTTP. This works whether the provider publishes advertisements over dtsync or httpsync.
> Add command to publish announce message via HTTP

- cmd/provider/internal/client_store.go
- engine/chunker/cached_chunker_test.go
- engine/chunker/chain_chunker.go
- engine/engine.go
- engine/linksystem_test.go
- go.mod
- go.sum
Upgrade to latest `go-legs` to fix an issue in `provider` CLI when given
HTTP provider multiaddr.
Upgrade to the latest storetheindex to take advantage of schema
simplifications. Reflect changes in the schema API.
> Upgrade indexing dependencies

- README.md
Executing `go install github.com/filecoin-project/index-provider@latest` returns `package github.com/filecoin-project/index-provider is not a main package`. 
The correct command should be `go install github.com/filecoin-project/index-provider/cmd/provider@latest`.
> Fix CLI install command

- cmd/provider/import.go
The CLI sends the car path to the daemon for import. The daemon may not resolve relative car paths if the CLI and daemon run in different working folders.
The proposed solution is the CLI to resolve the relative path to an absolute path before sending it to the daemon.
> Support relative paths for car import

- go.mod
- go.sum
- mirror/doc.go
- mirror/mirror.go
- mirror/mirror_api_test.go
- mirror/mirror_env_test.go
- mirror/mirror_test.go
- mirror/options.go
- mirror/selectors.go
- mirror/store.go
- multihash_iterator.go
Implement the ability to periodically check the advertisement chain
published by an index provider an mirror it with optional remapping of
the original entries in HAMT or entry chunk.
Host the original ad chain in the mirror such that the mirror can also
act as a CDN for the original ad chain.
Implement a mirror testing environment that asserts various
configuration permutations function as expected.
Implement utilities to extract `MultihashIterator` from links stored by
an IPLD link system regardless of the underlying entries type.
> Mirror an existing provider with optional entries remap and CDN

- cmd/provider/import.go
If the import car key is not specified by the user, it is currently calculated as a hash of the unclean car path.
So different paths to the same file would produce a different key and hence a different ad for the very same content.
For example, importing:
my.car
./my.car
../my.car
/abs/path/to/my.car
will result in a different ad although these paths point to the same file.
It would be better if the absolute car file path is used to determine the import car key.
> Calculate import cart key from the absolute car file path instead of raw path flag value

- engine/engine.go
This PR fixes index keys so that they are compatible with the future Remove All support. This is required to be able to do range queries by provider for index clean up.
> Fixed index keys so that they are compatible with the future Remove All support

- go.mod
- go.sum
Upgrade to the latest go-legs and go-ipld-prime so that the versions used are consistent with the ones in storetheindex.
> Upgrade go-legs and IPLD

- mirror/mirror.go
Convert the mirror durations to millisecond to match the destination metric unit.
> Convert to metric unit before recording

- cmd/provider/daemon.go
- cmd/provider/index.go
- cmd/provider/internal/config/identity.go
- cmd/provider/internal/config/identity_test.go
- cmd/provider/internal/config/init_test.go
- cmd/provider/register.go
The PR adds an ability to read a private key from a file if one hasn't been provided in the json config (similarly to `storetheindex`). If a key is neither in the config or a file - a new key is going to be generated and saved to the disk. 
Path to the file with private key is driven by `INDEXPROVIDER_PRIV_KEY_PATH ` environment variable. If neither config nor the var have been provided - the program will error out. 
This functionality has been requested by `bifrost-infra` in their efforts to automate `index-provider` deployments. CC @hsanjuan
> Auto generate identity if one hasn't been provided in json config

- README.md
- cmd/provider/daemon.go
- cmd/provider/internal/config/config.go
- cmd/provider/internal/config/init.go
- cmd/provider/internal/config/reframe.go
- go.mod
- go.sum
- reframe/chunker.go
- reframe/cid_queue.go
- reframe/ds_wrapper.go
- reframe/listener.go
- reframe/listener_api_test.go
- reframe/listener_concurrency_test.go
- reframe/listener_test.go
- reframe/stats_reporter.go
- server/reframe/http/options.go
- server/reframe/http/server.go
This PR adds a capability for exposing a [reframe server](https://github.com/ipfs/go-delegated-routing) from the index-provider daemon. Reframe server allows IPFS node to advertise its contents to indexers alongside DHT via the [delegated routing protocol](https://github.com/ipfs/specs/blob/main/reframe/REFRAME_PROTOCOL.md) . 
Reframe server can optionally be exposed as a part of `daemon` command by adding a `Reframe` configuration block, which is off by default. 
Kubo advertises its content via snapshots containing all of its CID.  Snapshots are re-published every 12 hours. Single CIDs can also be advertised upon pinning to the node. The reframe server chunks up the received CIDs and advertises them to the indexers via the `NotifyPut` as chunks get full. A chunk maps one-to-one to an …
> Added implementation for the IPFS index provider

- reframe/ds_wrapper.go
- reframe/listener.go
- reframe/listener_api_test.go
- reframe/listener_test.go
- reframe/options.go
- reframe/options_test.go
Split reframe snapshot into multiple chunks as leveldb has a constraint on maximum size of binary blobs.
> Split reframe snapshot into multiple chunks

- cmd/provider/index.go
- metadata/http.go
allows `provider index` to specify a base64 metadata indicating an HTTP multicodec
> Support manual indexes on a provider signalling an HTTP metadata codec

- reframe/listener.go
- reframe/listener_api_test.go
- reframe/listener_test.go
Some CID timestamps might be missing from the CID index / snapshot if the index-provider has been abruptly stopped before the latest snapshot got persisted. In that case - backfill those CIDs with the current timestamp on initialisation so that they match the published ads. This is safe to do. Even if they have expired, they'd still expire just at a later date.
> Backfill missing reframe CID timestamps

- cmd/provider/fsutil.go
- cmd/provider/internal/client.go
- cmd/provider/internal/config/ingest.go
- cmd/provider/mirror.go
- e2e_retrieve_test.go
- engine/doc.go
- engine/engine.go
- engine/engine_test.go
- go.mod
- go.sum
- mirror/doc.go
- mirror/mirror.go
- mirror/mirror_env_test.go
- mirror/mirror_test.go
- mirror/options.go
- mirror/selectors.go
- testutil/testutil.go
All functionality from go-legs has moved to storetheindex/dagsync.
For tests, bind libp2p hosts to local interface to avoid problems with testing when using various VPNs.
> Replace dependency on go-legs with storetheindex

- README.md
- engine/engine_test.go
- engine/linksystem_test.go
- engine/xproviders/xproviders.go
- engine/xproviders/xproviders_test.go
- go.mod
- go.sum
- reframe/listener_concurrency_test.go
- reframe/listener_test.go
- testutil/testutil.go
This PR adds support for [extended providers](https://github.com/filecoin-project/storetheindex/pull/804/files). It's a *programmatic* API only. CLI and configuration support will follow up if there going to be a need for those. 
In particular, the PR adds `xproviders.AdBuilder` class - a builder for constructing, signing and verifying an ad that can be then published using `Engine`.
> Add extended providers support

- engine/xproviders/xproviders.go
- engine/xproviders/xproviders_test.go
It should be possible to have only main provider in the EPs list. This feature is required if a provider would like to announce a new protocol available on different endpoints.
> Allow to have only main provider in the extended list

- cmd/provider/daemon.go
- cmd/provider/internal/config/reframe.go
- reframe/ds_wrapper.go
- server/reframe/http/server.go
Propagate page size to reframe configuration so that it can be changed without redeploying the service
> Add page size configuration option

- reframe/chunker.go
- reframe/cid_queue.go
- reframe/listener.go
- reframe/listener_api_test.go
- reframe/listener_test.go
Fixed a bug when the same cids have been readvertised over and over again that has led to high disk and RAM usage. Removed some indexes that should improve RAM profile.
Fixes https://github.com/protocol/bifrost-infra/issues/2255
CC @gmasgras
> Improve reframe memory consumption

- engine/chunker/cached_chunker.go
- engine/chunker/chunker.go
- engine/chunker/hamt_chunker.go
- engine/linksystem.go
Generated entries link from a multihash lister are cached and eventually evicted. They are then regenerated from the original lister whenever required via IPLD link system. The multihash lister, therefore, must be consistent: it must return the same list of multihashes for the same key in order to assure that the link generated will match the previously generated links as mandated by immutable content-addressable data representation as IPLD nodes.
The chages introduced firstly allow chunker interface to return no errors with nil link if a given lister has no elements, and additionally asserts that the link returned by the chunker matches the link expected by the IPLD link system.
An explicit error type is exported to signal mismatch of links and tell the user that the lister is behaving …
> Error explicitly when mutlihash lister behaves inconsistently

- cmd/provider/list.go
Print metadata length in `provider ls` command to help with debugging.
> Print metadata length in list ad

- cmd/provider/internal/client_store.go
- cmd/provider/list.go
Update the ad list command to print extended providers.
fixes https://github.com/ipni/index-provider/issues/314
> Update `provider ls` to print extended providers

- cmd/provider/list.go
To help debug publisher/provider issues also print the context ID in order to reason about correctness of metadata absence among other things.
> Print context ID in `provider ls` command

- engine/xproviders/xproviders.go
- engine/xproviders/xproviders_test.go
* Don't allow empty metadata or addresses in the extended provider body
* Don't add the main provider as extended if it's already on the list
* Don't add extended providers at all if non has been provided explicitly
Fixes https://github.com/ipni/index-provider/issues/318
CC @dirkmc
> Fix bug in xproviders builder

- cmd/provider/internal/client.go
Similar to the indexer ingest logic, skip over entries links that are not found, and log a warn message so that the user is aware.
Fixes #323
> Skip over entries link that are not found

- cmd/provider/daemon.go
- engine/options.go
The provider daemon was not using the RetrievalMultiaddrs from the configuration file. This caused its advertisements to only contain the local addresses from the host, which would not be acceptable if the host is behind a gateway or NAT.
> Daemon needs to use RetrievalMultiaddrs from configuration

- go.mod
- go.sum
- server/admin/http/announce_handler.go
- server/admin/http/car_handler.go
- server/admin/http/connect_handler.go
- server/admin/http/server.go
There is no benefit to using gorilla/mux for this, so use stdlib http.ServeMux.
> Move from gorilla/mux to http.ServeMux

- README.md
- cmd/provider/daemon.go
- cmd/provider/internal/config/config.go
- cmd/provider/internal/config/init.go
- cmd/provider/internal/config/reframe.go
- delegatedrouting/chunker.go
- delegatedrouting/cid_queue.go
- delegatedrouting/ds_wrapper.go
- delegatedrouting/listener.go
- delegatedrouting/listener_api_test.go
- delegatedrouting/listener_concurrency_test.go
- delegatedrouting/listener_test.go
- delegatedrouting/options.go
- delegatedrouting/options_test.go
- delegatedrouting/stats_reporter.go
- go.mod
- go.sum
- server/delegatedrouting/server/options.go
- server/delegatedrouting/server/server.go
Upgrade from reframe to http delegated rotuing as reframe isn't supported by kubo anymore. Datastore is backwards compatible.
Tested with Kubo v0.19.0.
Fixes https://github.com/ipni/index-provider/issues/312
> Upgrade to http delegated routing

- cmd/provider/daemon.go
- cmd/provider/internal/config/delegatedrouting.go
- delegatedrouting/chunker.go
- delegatedrouting/listener.go
- delegatedrouting/listener_test.go
- delegatedrouting/options.go
- server/delegatedrouting/server/options.go
- server/delegatedrouting/server/server.go
Currently the last chunk gets stuck in the delegated routing server until it's full. That might take a long time given that re-provide is relatively infrequent. This commit adds a worker that periodically checks the current chunk and publishes it if it's not empty and is old enough.
* Add a new configuration parameter `AdFlushFrequency` that defaults to 10 minutes
* Add a worker to delegated routing listener that periodically checks the current chunk
> Add periodic ad flush

- cardatatransfer/cardatatransfer_test.go
- delegatedrouting/listener_concurrency_test.go
- delegatedrouting/listener_test.go
- engine/chunker/benchmark_test.go
- engine/chunker/cached_chunker_test.go
- engine/chunker/chain_chunker_test.go
- engine/chunker/hamt_chunker_test.go
- engine/engine_test.go
- engine/linksystem_test.go
- engine/xproviders/xproviders_test.go
- go.mod
- go.sum
- mirror/mirror_env_test.go
- mirror/mirror_test.go
- server/admin/http/car_handler_test.go
- testutil/testutil.go
The logic is simpler to call because random generators do not need a random generator as an argument. Avoids having the same test code in multiple places.
> Use logic located in go-libipni/test

- delegatedrouting/chunker.go
- delegatedrouting/ds_wrapper.go
- delegatedrouting/listener.go
- delegatedrouting/listener_api_test.go
- delegatedrouting/listener_test.go
* Chunks for removed advertisements aren't stored in the datastore anymore, that will allow to improve initialisation time significantly especially for long running nodes;
* Fixes a bug when chunks got paged incorrectly on initialisation. That resulted into some chunks not being loaded at all and some got duplicated;
* Fixes a bug when chunk hasn't been assigned to CIDs on initialisation which resulted into all CIDs being treated was "new".
> Some improvements to index provider delegated routing

- engine/xproviders/xproviders.go
- engine/xproviders/xproviders_test.go
This PR adds a `WithEntries` method to the extended provider advertisement builder that allows it to set advertisement entries.
Fixes https://github.com/ipni/storetheindex/issues/1725
> feat: allow extended provider ad builder to set ad entries

- Makefile
- cmd/provider/provider.go
- version.go
The version is provided by the version.json file and the revision information is build into the binary by the compiler. Use this information instead of fetching it from github each build.
- Installed binary has version information.
- Builds work even without connectivity to github.
> Get version information from embedded build info

- README.md
See [this](https://github.com/ipni/index-provider/pull/372) for context
> Add Disclaimer to the Kubo integration doc

- engine/engine.go
- engine/linksystem.go
- engine/linksystem_test.go
In a case where no provider identity is found, skip over the entry to unblock ad processing.
> Return `ipld.ErrNotExists` when no provider identity is found

- engine/engine.go
- engine/linksystem.go
- engine/linksystem_test.go
Rebase the latest patch fixes released as part of `v0.11.3` onto `main`.
> Rebase patch release fixes onto `main`

- engine/engine.go
- engine/options.go
Ref: https://github.com/ipni/go-libipni/pull/56
No tests in here yet. Not sure how best to go about doing that.
This allows `Engine` to be used in a more passive move via HTTP. Set it up, attach it to an existing server, and let it run. See. https://github.com/ipld/go-frisbii for how I'm using this, currently with forks of both engine and httpsync to make it work.
> feat: http publisher without fully setting up server

- cmd/provider/connect.go
- cmd/provider/daemon.go
- cmd/provider/import.go
- cmd/provider/internal/config/announce.go
- cmd/provider/remove.go
- doc/publisher-config.md
- engine/engine.go
- engine/options.go
- go.mod
- go.sum
Make it optional to send announcements via gossip pubsub, instead of always sending them if a libp2p host is present.
This PR also separates announcement sender configuration from publisher configuration.
Other minor updates:
- Always close http response body
- Update go-libp2p and go-libipni
Fixes issue #364
Note: new options and config file remain backward-compatible with boost and with previous indexer-provider installations.
> Option to enable/disable pubsub announcement

- engine/linksystem.go
- engine/options.go
When a storage read error happens, the calling application can now invoke a custom piece of logic to fix that error in-flight.
> Add a hook to fix multihash mismatch errors

- engine/linksystem.go
- go.mod
- go.sum
Read the schema type hint from the IPNI sync request header, and if provided, compare it against the type of data retrieved.
> Read schema type hint from sync request
