ipni/index-provider

- core/engine/engine.go
- core/engine/engine_test.go
- go.mod
- go.sum
- Upgrade to latest schema
- Removed graphSupport flag
> Upgrade to latest schema

- command/daemon.go
- core/engine/engine.go
- core/engine/engine_test.go
- core/interface.go
- go.mod
- go.sum
This should be a quick one:
- Upgrades dependencies.
- Integrates engine in daemon.
> Upgrade go-legs. Integrate engine in daemon

- command/daemon.go
- command/flags.go
- command/net.go
- config/addresses.go
- config/config.go
- config/init.go
- go.mod
- go.sum
- main.go
- server/http/handler.go
- server/http/models.go
- server/http/options.go
- server/http/server.go
This PR:
- Implements an http server for admin purposes.
- Implements a command to attempt connections to indexer nodes (or any other libp2p node)
- Does some housekeeping to the daemon.
> Admin server, connect command in CLI

- core/engine/engine.go
- core/engine/engine_test.go
- core/engine/linksystem.go
- core/interface.go
- go.mod
- go.sum
- internal/suppliers/callback.go
- server/libp2p/protocol_test.go
This PR:
- Adds support for the advertisements of indexed data as linked lists.
- Modifies callback interface to return channels.
_// Thanks @masih for the debugging support._
> Support for linked lists advertisement.

- core/engine/engine_test.go
- core/engine/linksystem.go
- core/interface.go
- internal/suppliers/callback.go
- internal/suppliers/callback_test.go
- server/http/models.go
Integrate the CAR supplier with callback channel interface and change
the callback API to be a directional channel
> Integrate CAR supplier with callback channel

- server/http/error.go
- server/http/importcar_handler_test.go
- server/http/io.go
Fix an issue where http header is written after body which forces status
code 200.
> Fix admin server header written after body

- core/engine/engine_test.go
> core/engine: ignore fewer errors

- core/engine/engine.go
- core/engine/engine_test.go
- go.mod
- go.sum
> mod: go-legs has moved

- index_mh_iter.go
- index_mh_iter_test.go
> ensure CarMultihashIterator sorts CIDs by offset

- cmd/go.mod
- cmd/go.sum
- go.mod
- go.sum
Upgrade to the latest `storetheindex` in both root and `cmd` modules.
> Upgrade to the latest `storetheindex`

- version.json
Make a tagged release to have a tag associated with the integration of
new go-legs and storetheindex into index-provider.
> Make v0.2.0 release

- cardatatransfer/doc.go
- cardatatransfer/stores/stores.go
- cmd/provider/doc.go
- engine/doc.go
- engine/engine.go
- interface.go
- metadata/doc.go
- server/admin/http/doc.go
- supplier/car_supplier.go
- supplier/doc.go
- version/version.go
Add missing documentation and alter as needed.
> Update godoc across packages

- cmd/provider/internal/client_store.go
right now we are only using dag-json, but we (or others) may eventually use dag-cbor
> Lookup which decoder to use instead of always using dag-json

- version.json
Bump minor version in preperation for release.
> Tag the head of master in preparation for release

- cmd/provider/daemon.go
- engine/engine.go
> Publish the latest advertisement on engine start

- version.json
Make a release for the fix to #145
> Bump version for release

- cmd/go.mod
- cmd/go.sum
- go.mod
- go.sum
- version.json
Upgrade dependencies to legs and sti to latest and bump version for release.
> Upgrade to the latest `storetheindex` and `go-legs`

- version.json
Bump version file to make a release and have binaries autogenerated.
> Bump version to tag and release with binaries attached

- cmd/provider/verify_ingest.go
If enabled, print the unindexed multihashes. But only print them if
connection to indexer was successful and the multihashes were deemed to
be unseen.
Collect errors as part of verification result and print them out for
better traceability.
> Add a flag to print the unindexed multihashes during verify

- supplier/car_supplier.go
- supplier/car_supplier_test.go
The CAR supplier regenerated the index if it did not contain identity
CIDs, i.e. the fully-indexed characteristic was missing in CARv2 header.
See: https://github.com/filecoin-project/index-provider/issues/118
Fixes: #118
> Relax the need for full index in car supplier

- .github/workflows/automerge.yml
- .github/workflows/go-check.yml
- .github/workflows/go-test.yml
- cmd/go.mod
- cmd/go.sum
- go.mod
The most recent upgrade of Unified CI files in this repository required a human intervention. Hence, this PR from a fork I created. Here are the additional changes that I had to add to make the upgrade (in particular, Go version upgrade) succeed:
- https://github.com/filecoin-project/index-provider/commit/1976c5f3290511b4fcb6d5dfb07e572680573735
- https://github.com/filecoin-project/index-provider/commit/8d5d7de7d764de90a2fc954b4a6b63d9570db41e
- checks: https://github.com/galargh/index-provider/actions/runs/2102295966
- test: https://github.com/galargh/index-provider/actions/runs/2102295967
> sync: update CI config files

- engine/engine.go
- engine/options.go
> allow option specifying provider addrinfo

- engine/linksystem.go
Markets log is being spammed with (IMHO useless) lines
> Make linksystem less noisy

- .gitignore
- Makefile
- Also, do not ignore directory called "provider"
> Restore TAG in makefile after discussion

- version.json
Bump version to release the latest fix to caching mechanisms.
> Bump version in preparation for release

- engine/engine.go
Format and improve some wording.
> Format comments

- cmd/provider/mirror.go
- cmd/provider/provider.go
- engine/engine_test.go
- go.mod
- go.sum
- mirror/mirror.go
- mirror/options.go
Add `provider mirror` command along with flags to set all possible
mirror options.
> Implement the ability to run a mirror via `provider mirror` CLI

- .github/workflows/ecr-publisher.yml
Added publishing to ECR public alongside ECR private
> Added publishing to ECR public

- .github/workflows/goreleaser-check.yml
- .github/workflows/goreleaser-snapshot.yml
- .github/workflows/releaser-bin.yml
Bump the go version used by `goreleaser` to match the root go module version.
> Bump go version used by `goreleaser`

- reframe/ds_wrapper.go
- reframe/listener.go
Removing individual expired CIDs from datastore is too expensive. Switched to persisting the whole snapshot on clean ups instead, given that normally a large portion of CIDs expires in the same time.
> Stop removing individual expired reframe CIDs from datastore

- engine/engine.go
- engine/engine_test.go
Fixes https://github.com/ipni/index-provider/issues/360
> Fix a bug when default provider identity hasn't been assumed in the link system

- engine/engine.go
> Fix incorrect log message and comment
